import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "./providers";
import Header from "./Header";
import Hr from "@/app/components/Hr";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body
				className={`${inter.className} mx-auto min-h-screen w-full max-w-screen-lg bg-white p-4 dark:bg-black sm:p-10`}
			>
				<Providers>
					<Header />
					<Hr />
					{children}
				</Providers>
			</body>
		</html>
	);
}
