import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "./providers";
import Header from "./Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body
				className={`${inter.className} min-h-screen w-full max-w-screen-lg mx-auto p-4 sm:p-10 bg-white dark:bg-black`}
			>
				<Providers>
					<Header />
					<hr className='h-px border-0 bg-slate-300 dark:bg-slate-800 bg' />
					{children}
				</Providers>
			</body>
		</html>
	);
}
